### ISSUE TITLE
Load balancer for bare-metal cluster

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/issues#13]
In order to expose services, we need load balancers. However, load balancers are not provided by Kubernetes but by cloud services like AWS. (c.f. http://rafabene.com/2015/11/11/how-expose-kubernetes-services/) This is the reason that when we run Kubernetes on Vagrant VM clusters, we can only expose services by NodePort (c.f., https://github.com/k8sp/vagrant-coreos).  Therefore, we need to figure out how to create the load balancer for our bare-metal cluster.

A possibly useful link: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

A reference implementation (AWS load balancer): https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws_loadbalancer.go

**Comment by Yancey0623** [comment]
Task List
- [x] 调研 https://github.com/kubernetes/contrib/tree/master/service-loadbalancer
- 无法满足需求，暂时放弃。
- [x] 调研 https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

**Comment by Yancey0623** [comment]
我们对loadbalancer的需求主要有以下几点：
1. 通过DNS服务商，将二级域名转发到我们的前端机上，loadbalancer的服务就部署在这些前端机上面，属于Kubernetes集群的一部分。
2. 支持7层的反向代理，例如我们的二级域名是bfdcloud.com,那么我们的应用可以是a.bfdcloud.com，1.a.bfdcloud.com这样自定义的域名。
3. 支持4层TCP代理，外网可以直接通过这个TCP的地址访问我们后端的Pod。
4. 能够根据后端Pod地址变化动态的reload新的配置信息。

通过对 https://github.com/kubernetes/contrib/tree/master/service-loadbalancer 这个实现的调研，我们发现对7层反向代理的支持没有那么友好，例如
1. 无法自定义域名，命名规则都是要按照`http://{domain}/{service_name}`这样的规则进行，无法满足我们自定义应用域名的需求。

**Comment by Yancey0623** [comment]
- 通过调研,Nginx Ingress Controller可以满足我们的需求，[Nginx Ingress Controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx).'
- 这个PR里有一个发布Web App的例子https://github.com/k8sp/kubernetes-examples/pull/3
