### ISSUE TITLE
Run Hadoop on a k8s with 3 node, with flannel overlay network

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/issues#16]
- [x] 1. deploy a k8s cluster with multi workers, <del>using docker(centos 7)</del> using coreos.
- [x] 2. deploy hadoop master and slave on the cluster and be able to run MR jobs
- [ ] 3. run performance test,  compare to the cluster deployed on the same nodes without k8s

working on this repo: https://github.com/k8sp/hadoop

**Comment by typhoonzero** [comment]
Found out the docker-multi node init scripts tend to use /etc/sysconfig/docker as docker daemon options, but systemd not setting up properly. Going through: https://docs.docker.com/engine/admin/systemd/, failed at:

```
service docker status
Redirecting to /bin/systemctl status  docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─docker.conf
   Active: failed (Result: exit-code) since Wed 2016-05-18 11:45:51 CST; 14min ago
     Docs: https://docs.docker.com
  Process: 32377 ExecStart=/usr/bin/docker daemon -H fd:// $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $BLOCK_REGISTRY $INSECURE_REGISTRY (code=exited, status=1/FAILURE)
 Main PID: 32377 (code=exited, status=1/FAILURE)

May 18 11:45:51 hlg-3p165-wuyi systemd[1]: Starting Docker Application Container Engine...
May 18 11:45:51 hlg-3p165-wuyi docker[32377]: /usr/bin/docker: "daemon" requires 0 arguments.
May 18 11:45:51 hlg-3p165-wuyi docker[32377]: See '/usr/bin/docker daemon --help'.
May 18 11:45:51 hlg-3p165-wuyi docker[32377]: Usage:        docker daemon [OPTIONS]
May 18 11:45:51 hlg-3p165-wuyi docker[32377]: Enable daemon mode
May 18 11:45:51 hlg-3p165-wuyi systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
May 18 11:45:51 hlg-3p165-wuyi systemd[1]: Failed to start Docker Application Container Engine.
May 18 11:45:51 hlg-3p165-wuyi systemd[1]: Unit docker.service entered failed state.
May 18 11:45:51 hlg-3p165-wuyi systemd[1]: docker.service failed.
```

any ideas?

**Comment by typhoonzero** [comment]
problems solved today: 
using flannel to setup overlay network, see: https://github.com/coreos/flannel
the script under docker-multi(http://kubernetes.io/docs/getting-started-guides/docker-multinode/) uses legacy /etc/sysconfig/docker file to setup "docker0" bridge network options(mtu, bip). But CentOS7 uses systemd to manage docker.service. Inorder to start docker with flannel, need to modify the systemd drop in files: "/etc/systemd/system/docker.service.d/docker.config", and add:

```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --mtu=1450 --bip=10.1.99.1/24
```

the options was generated by the master.sh or worker.sh, after flannel docker service started.
do

```
sudo systemctl daemon-reload
sudo systemctl restart docker
```

then the nodes can reach each other

Then encountered "HTTP probe failed with statuscode: 503" when setting up skydns on the cluster,
ensure to do this before create the skydns service to refresh certs

```
$ kubectl get secrets  --all-namespaces
NAMESPACE     NAME                  TYPE                                  DATA
default       default-token-6oahq   kubernetes.io/service-account-token   2
kube-system   default-token-ur28n   kubernetes.io/service-account-token   2

$ kubectl delete secret --namespace=default default-token-6oahq
$ kubectl delete secret --namespace=kube-system  default-token-ur28n
```

**Comment by Yancey0623** [comment]
this issue depends #27 , task3 can be continued after network performance test.  I will close this issue now.
