### ISSUE TITLE
Understanding Flannel

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/issues#18]
Reading list:
- https://github.com/coreos/flannel#flannel
- http://blog.oddbit.com/2014/08/11/four-ways-to-connect-a-docker/

To close this issue, we want a PR that contains a document that clearly describes knowledge in at least above two documents.

**Comment by typhoonzero** [comment]
Closing this for we have: https://github.com/k8sp/kubernetes/blob/master/networking/flannel.md
