### ISSUE TITLE
Run Hadoop MapReduce and YARN on CoreOS single-node cluster

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/issues#2]
https://github.com/Yancey1989 is working on this issue in repo https://github.com/k8sp/hadoop

**Comment by typhoonzero** [comment]
There's still lots to do to move on to cluster

**Comment by Yancey0623** [comment]
1. Add hadoop example with https://github.com/k8sp/hadoop/pull/5. 
2. Here is the deploy steps:https://github.com/k8sp/hadoop.

**Comment by Yancey0623** [comment]
I think this issue can be closed, hadoop on k8s cluster will move to the issue #16
