### ISSUE TITLE
Elasticsearch on kubernetes + coreos cluster

### ISSUE THREAD

**Issue by Yancey0623** [k8sp/issues#21]

**Comment by sparklxb** [comment]
预计下周内搞定

**Comment by wangkuiyi** [comment]
@sparklxb 最好能说明一下
1. 预计需要做的事情
2. 根据每件事情估计一个精确（到小时）的预期

预期可以修改，因为大家都是新手，和可能估计不准确，但是要有一个精确预期，这样帮助我们了解自己的设想和实际时间之间的差异，不断注意到这样的差异，帮助我们从新手变成熟手，最后成为能带一个团队独当一面的高手。

**Comment by sparklxb** [comment]
@wangkuiyi 不好意思，才看到信息。
已做：
1.在真实集群部署，https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/elasticsearch （es 1.7.1，有点旧且image修改过代码），功能和容错没问题；
注：此image的作者也在维护新的版本，https://github.com/pires/kubernetes-elasticsearch-cluster ，真实集群测试2.3.2，也没问题。
2.https://github.com/k8sp/hadoop/tree/master/init 在vagrant里部署多节点，kube-proxy转cluster ip会有问题（表现为在任意pod连cluster ip:port连不上，kube-proxy写的iptable也不对，DNAT用的是eth0，而VirtualBox的eth0用作NAT非hostonly），暂时解决不了。暂时不清楚https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.htm l这种方法会不会有问题或者怎么解决的。待有空翻墙把image搞下来试试。

计划：
1. 制作es最新版本的docker镜像，并部署测试 1天；（用官方es images https://hub.docker.com/_/elasticsearch/  试试）
2.写脚本测试es性能 1天；
3.整理相关的文档 半天。

**Comment by sparklxb** [comment]
@wangkuiyi 
文档及dockerfile https://github.com/sparklxb/docker-elasticsearch-kubernetes

目前采用的kubernetes网络性能不佳，集群es性能未测。
Kubernetes Cloud Plugin for Elasticsearch ( https://github.com/fabric8io/elasticsearch-cloud-kubernetes )有点意思，有空再深入。

**Comment by sparklxb** [comment]
经过实际测试,可以关闭了
