### ISSUE TITLE
Kafka on kubernetes + coreos cluster

### ISSUE THREAD

**Issue by Yancey0623** [k8sp/issues#22]

**Comment by zhengbo0** [comment]
争取下周完成

**Comment by wangkuiyi** [comment]
@zhengbo0 最好能说明一下
1. 预计需要做的事情
2. 根据每件事情估计一个精确（到小时）的预期

预期可以修改，因为大家都是新手，和可能估计不准确，但是要有一个精确预期，这样帮助我们了解自己的设想和实际时间之间的差异，不断注意到这样的差异，帮助我们从新手变成熟手，最后成为能带一个团队独当一面的高手。

**Comment by zhengbo0** [comment]
- 学习制作kafka的docker镜像 1天
- 学习以docker file的形式制作docker镜像，并写启动脚本 1天
- 尝试用kubernetes部署kafka集群 1天
- 尝试用kubernetes部署zookeeper集群 1天
- 尝试往kafka导入测试数据，测试集群环境 半天
- 整理相关的文档  半天

**Comment by zhengbo0** [comment]
#### 目前已完成进度
- 通过dockerfile制作flume,kafka镜像，并测试数据从单节点flume容器到单节点kafka容器正确通信
- 通过kubernetes部署单节点kafka

#### 正在做的
- 通过kubernetes部署kafka集群和zookeeper集群
- 通过kubernetes部署的flume zookeeper kafka多个集群中间可以正确通信

#### 下一步要做的
- 自己手动部署一套多节点的kubernetes环境

#### 目前存在的问题
- 笔记本不能翻墙，上传和下载镜像比较慢

**Comment by zhengbo0** [comment]
### 本周进展

##### 已完成
- 完成通过kubernetes部署kafka集群和zookeeper集群，并将kafka集群和zookeeper集群整合

##### 正在做
- kubernetes部署flume集群,并测试数据流通过flume到kafka

##### 下一步
- 整理相关文档

**Comment by zhengbo0** [comment]
使用kubernetes部署单节点flume       https://github.com/zhengbo0/flume
kubernetes部署zookeeper集群          https://github.com/zhengbo0/zookeeper
使用kubernetes部署kafka集群           https://github.com/zhengbo0/kafka
目前测试是从单节点flume到kafka集群，数据流程已走通
