### ISSUE TITLE
Kubernetes master node HA

### ISSUE THREAD

**Issue by Yancey0623** [k8sp/issues#26]
[x] 在多个节点上启动kubernetes master进程(api-server, controller-manager, scheduler, kube-proxy)
[ ] 通过增加Service和Endpoint的方式达到api-server的负载均衡，并增加对每个api-server的健康检查
[ ] 通过HAProxy或Ingress方式做到api-server的负载均衡
[ ] 整体测试多master情况下，关闭一个master节点，集群不受影响

**Comment by zhengbo0** [comment]
http://kubernetes.io/docs/admin/high-availability/

**Comment by zhengbo0** [comment]
ingress是通过service去后端选取对应的pod,对于多台k8s master,想通过自定义的serivce去选取不同master上的endpoint,通过Labels:component=apiserver,provider=kubernetes 选取失效

**Comment by zhengbo0** [comment]
通过自定义service和endpoint组合使用，可以完成上面的需求
kube-service.yaml文件内容：

```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service"
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 443,
                "targetPort": 443
            }
        ]
    }
}
```

kube-endpoints.yaml文件内容：

```
{
    "kind": "Endpoints",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service",
        "labels": {
            "app": "k8s"
         }
    },
    "subsets": [
        {
            "addresses": [
                { "ip": "172.17.8.101" },
                { "ip": "172.17.8.102" }
            ],
            "ports": [
                { "port": 443 }
            ]
        }
    ]
}
```

一个新的问题是：master只有一台对外提供服务，另外一台处于休眠状态，一旦对外提供服务的master出现down机，备用master会切换成active状态，上面定义的service会分发请求，如果分发到备用master上会不会出现服务不可以用的状态

**Comment by zhengbo0** [comment]
通过官方网站http://kubernetes.io/docs/admin/high-availability/#replicated-api-servers
我们可以看到master api server 是同时提供服务的

```
At this point, you should have 3 apiservers all working correctly. If you set up a network load balancer, you should be able to access your cluster via that load balancer, and see traffic balancing between the apiserver instances.
```

对于修改群集状态组件，例如控制器管理器(controller-manager)和调度程序(scheduler)，同时只有一个实例运行

```
we are going to use a lease-lock in the API to perform master election. We will use the --leader-elect flag for each scheduler and controller-manager, using a lease in the API will ensure that only 1 instance of the scheduler and controller-manager are running at once.
```

执行 `etcdctl get /registry/services/endpoints/kube-system/kube-scheduler`

```
{"kind":"Endpoints","apiVersion":"v1","metadata":{"name":"kube-scheduler","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/endpoints/kube-scheduler","uid":"bdd26260-4997-11e6-9fb6-080027eaf841","creationTimestamp":"2016-07-14T07:51:15Z","annotations":{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"core-02\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-07-14T07:51:15Z\",\"renewTime\":\"2016-07-15T06:53:46Z\",\"leaderTransitions\":0}"}},"subsets":[]}
```

执行`etcdctl get /registry/services/endpoints/kube-system/kube-controller-manager`

```
{"kind":"Endpoints","apiVersion":"v1","metadata":{"name":"kube-controller-manager","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/endpoints/kube-controller-manager","uid":"be8d53fe-4997-11e6-9fb6-080027eaf841","creationTimestamp":"2016-07-14T07:51:16Z","annotations":{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"core-02\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-07-14T07:51:16Z\",\"renewTime\":\"2016-07-15T06:55:40Z\",\"leaderTransitions\":0}"}},"subsets":[]}
```

执行`etcdctl get /registry/services/endpoints/default/kubernetes`查看active master的endpoint

```
{"kind":"Endpoints","apiVersion":"v1","metadata":{"name":"kubernetes","namespace":"default","uid":"9d469999-4812-11e6-a2b9-080027eaf841","creationTimestamp":"2016-07-12T09:25:46Z"},"subsets":[{"addresses":[{"ip":"172.17.8.102"}],"ports":[{"name":"https","port":443,"protocol":"TCP"}]}]}
```

**Comment by zhengbo0** [comment]
目前存在两个问题：
１，只有一个master对外提供服务，面临高并发时，如何处理？
２，如何动态检测到那个master是活跃状态？

**Comment by typhoonzero** [comment]
只有一台提供服务，是说master的所有组件？还是说scheduler, controller manager是，apiserver不是呢？

**Comment by zhengbo0** [comment]
官方说scheduler, controller manager同时只有一个实例提供服务，我测试时发现api server不是同时提供服务，只有一台可用

**Comment by zhengbo0** [comment]
发现上面的自定义service和endpoint组合使用很不稳定，导致测试结果不准确，api server确实是同时工作的，scheduler, controller manager同时只有一个服务
![qq 20160715165854](https://cloud.githubusercontent.com/assets/14144704/16869368/fcaab3a0-4aae-11e6-8a29-ca97cddaf179.png)

**Comment by zhengbo0** [comment]
测试自定义的自定义service和endpoint组合使用不稳定的原因是：service只能将请求转发到所在master node上的endpoint，无法转发到别的master node 上的endpoint。
发现官网有如下解释

```
The CIDR network to use for service cluster VIPs (Virtual IPs). Each service will be assigned a cluster IP out of this range. This must not overlap with any IP ranges assigned to the POD_NETWORK, or other existing network infrastructure. Routing to these VIPs is handled by a local kube-proxy service to each host, and are not required to be routable between hosts.
```

重点看最后一句，就是说service的vip地址，只能通过它节点的kube-proxy路由，不需要路由到主机之间

**Comment by zhengbo0** [comment]
master A 节点 service range 设的是10.3网段，master B 节点设置的 service range 10.4网段，发现master B节点设置的没有生效　`etcdctl get /registry/ranges/serviceips`,发现etcd里面只记录了10.3网段

```
{"kind":"RangeAllocation","apiVersion":"v1","metadata":{"creationTimestamp":null},"range":"10.3.0.0/24","data":"AQ=="}
```

master B节点执行 `kubectl get svc`

```
kubernetes   10.3.0.1     <none>        443/TCP   2d
```

执行`kubectl describe svc  kubernetes`

```
Name:           kubernetes
Namespace:      default
Labels:         component=apiserver,provider=kubernetes
Selector:       <none>
Type:           ClusterIP
IP:         10.3.0.1
Port:           https   443/TCP
Endpoints:      172.17.8.102:443
Session Affinity:   None
No events.

```

**Comment by typhoonzero** [comment]
master B 节点设置的 service range 10.4网段是哪个参数指定的？是否需要也设置成10.3的呢

**Comment by zhengbo0** [comment]
通过SERVICE_IP_RANGE指定的

**Comment by typhoonzero** [comment]
启动api-server时的参数？

**Comment by zhengbo0** [comment]
通过`iptables -L -n -t nat`查看本地虚拟机上的nat转发rules，发现没有问题，但是转发一直有问题，猜测是本地虚拟机出现问题。
尝试在物理机器上部署两个master，通过自定义service 和endpoint的方式测试，发现可以正常转发到不同的endpoint，同样通过`iptables -L -n -t nat`查看本地物理机上的nat转发rules，和虚拟机上的并没有发现什么不同。很奇怪为什么会出现这种问题，需要进一步排查。

**Comment by zhengbo0** [comment]
又发现vagrant虚拟机一个坑，在coreos虚拟机上启动k8s　master后，默认没有pod运行
![qq 20160729195128](https://cloud.githubusercontent.com/assets/14144704/17247435/e49a6644-55c5-11e6-9b07-423d3ac95b25.png)
而k8s　master在物理机上默认会起一个pod，这个pod会启动四个Container:kube-apiserver,kube-controller-manager,kube-scheduler,kube-proxy
![qq 20160729200423](https://cloud.githubusercontent.com/assets/14144704/17248149/ff0c8c96-55ca-11e6-91eb-334ac5881e02.png)
可以通过命令`kubectl describe pod kube-controller-172.24.3.220`查看pod中有那些容器
![qq 20160729203143](https://cloud.githubusercontent.com/assets/14144704/17248309/3ff6c6ee-55cc-11e6-980d-a20978de9274.png)

**Comment by zhengbo0** [comment]
现在尝试给k8s master起的那个pod打上标签，修改 /etc/kubernetes/manifests/下kubernetes_master.manifest文件，添加labels service: k8s

```
cd /etc/kubernetes/manifests/
vim kubernetes_master.manifest
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller
  labels:
    service: k8s
spec:
  hostNetwork: true
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: ssl-certs-kubernetes
.....
```

执行`./kubectl describe pod kube-controller-172.24.3.220`查看标签是否打上

```
Name:       kube-controller-172.24.3.220
Namespace:  default
Node:       172.24.3.220/172.24.3.220
Start Time: Fri, 29 Jul 2016 06:57:03 +0000
Labels:     service=k8s
Status:     Running
IP:     172.24.3.220
Controllers:    <none>
Containers:
.......
```

同理，对其他k8s master打上相同标签
自定义service,通过该service对master的pod做loadbalancer

```
apiVersion: v1
kind: Service
metadata:
  name: k8s
  labels:
    service: allk8s
spec:
  ports:
    - name: client
      port: 443
  selector:
    service: k8s
```

执行`kubectl create -f my-service.yaml`发布该service
`kubectl get svc`可以查看已发布的service

```
NAME              CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
codis-dashboard   10.100.0.2     nodes         18087/TCP   3h
codis-server4-1   10.100.0.17    <none>        6900/TCP    1d
codis-server5-1   10.100.0.169   <none>        6900/TCP    10h
k8s               10.100.0.119   <none>        443/TCP     1h
kubernetes        10.100.0.1     <none>        443/TCP     2d
```

`kubectl get ep`查看对应的endpoint

```
NAME              ENDPOINTS                           AGE
codis-dashboard   10.1.62.2:18087                     3h
codis-server4-1   10.1.62.4:6900                      1d
codis-server5-1   10.1.62.6:6900                      10h
k8s               172.24.3.220:443,172.24.3.221:443   1h
kubernetes        172.24.101.1:443                    2d
```

**Comment by zhengbo0** [comment]
172.24.3.220上通过systemctl stop docker,停止220上k8s的master,经过几十秒之后，发现service 
k8s对应的endpoint地址也会发生变化，３.220的endpoint地址会被删除掉

**Comment by xiaoping378** [comment]
i have a project called [k8s-deploy](https://github.com/xiaoping378/k8s-deploy), it can make a HA cluster.

**Comment by typhoonzero** [comment]
@xiaoping378 看到了，是一个很棒的项目。有兴趣在sextant中提交代码么？地址：https://github.com/k8sp/sextant

**Comment by xiaoping378** [comment]
@typhoonzero 
呃。。sorry，我现在主要精力在搞openshfit了
