### ISSUE TITLE
Test PXE Install CoreOS And Deploy K8S Worker Node On Office Environment

### ISSUE THREAD

**Issue by LestDou** [k8sp/issues#36]
The based environment automatic deploy (include coreOS and k8s worker node) should finished by PXE service as we planed, test the function of PXE is needed. The office environment might be 5 desktop(lack of server in our office), in one vlan at first. Multi vlan and classify of nodes automatic is the next step in future.  

Task List:
- [x] auto install coreos with pxe service
- [x] install k8s master node, fetch docker image and rkt aci from private registry.

**Comment by LestDou** [comment]
Add core.autologin in pxelinux.cfg/default cloud login when install progress up. In this way we can debug the install.sh

``` sh
label coreos

  menu default

  kernel 899.17.0/coreos_production_pxe.vmlinuz

  append initrd=coreos-stable/coreos_production_pxe_image.cpio.gz cloud-config-url=http://192.168.2.10/install.sh  coreos.autologin
```

**Comment by Yancey0623** [comment]
Task 2 done.
fetch docker image && aci from private registry: https://github.com/k8sp/auto-install/issues/28

**Comment by typhoonzero** [comment]
可以关了？cc修改的pr提交到auto-install如何？

**Comment by LestDou** [comment]
@typhoonzero ，ok，我close了
cc修改的我今天提交到auto-install
